# Generated by Django 5.0.1 on 2024-02-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_slug_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
