# Generated by Django 5.0.1 on 2024-02-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='discount',
        ),
    ]
