# Generated by Django 5.0.1 on 2024-02-08 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_category_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
