# Generated by Django 5.0.1 on 2024-02-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_products_productfeature_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfeature',
            old_name='product',
            new_name='products',
        ),
    ]
