# Generated by Django 5.0.1 on 2024-03-04 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
    ]
